name: Node.js Package

on:
  release:
    types: [published]

concurrency:
  group: npm-publish
  cancel-in-progress: false

jobs:
  cache-and-install:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          run_install: false

      - name: Install Node.js
        uses: actions/setup-node@v5
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Verify dependencies
        run: pnpm list

      - name: Build dist
        run: pnpm build

      - name: Verify build output
        run: ls -la dist/

      - uses: JS-DevTools/npm-publish@v4
        with:
          token: ${{ secrets.NPM_TOKEN }}
          access: public
          tag: latest
